###
GET http://localhost:3333/user/fetch

###
POST http://localhost:3333/user
content-type: application/json

{
  "email": "andrei@gmail.com",
  "password": "9167"
}

###
POST http://localhost:3333/user/create
content-type: application/json

{
  "email": "jarth@gmail.com",
  "password": "123"
}

###
POST http://localhost:3333/user/auth
content-type: application/json

{
  "email": "andrei@gmail.com",
  "password": "9167"
}

###
GET https://backend-versiculos.vercel.app/user/fetch

###
POST https://backend-versiculos.vercel.app/user/auth
content-type: application/json

{
  "email": "lucasandrei@gmail.com",
  "password": "1111"
}

###
POST https://backend-versiculos.vercel.app/user/create
content-type: application/json

{
  "email": "felipe@gmail.com",
  "password": "2222"
}
